import "./globals.css";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body suppressHydrationWarning>
                <h1 className="resp">
                    Lorem ipsum dolor, sit amet consectetur adipisicing elit.
                    Fugit, eius.
                </h1>
                {children}
            </body>
        </html>
    );
}
